name: Publish to npm (on main)

on:
  workflow_run:
    workflows: ["Lint and Test"]
    branches: [main]
    types:
      - completed

concurrency:
  group: publish-main
  cancel-in-progress: false

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Installs Deps & Build
        run: |
          set -e
          npm ci
          npm run build

      - run: npm publish --tag latest --access public --provenance
